language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 10
  - lts/*
  - node
deploy:
  - provider: npm
    email: twilio-ci@twilio.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: 10

notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms: $SLACK_TOKEN
